[package]
name = "local-ci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18.1"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0.79"
crossbeam-channel = "0.5.11"

# Need https://github.com/nix-rust/nix/pull/1297
# TODO - https://github.com/nix-rust/nix/issues/2280 - switch back to crates.io.
[dependencies.nix]
git = "https://github.com/nix-rust/nix.git"
rev = "172ca24"
features = ["process", "signal", "fs", "feature"]
